name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i -g yarn
    - run: yarn install
    - run: yarn build

    - env:
        FANDOM_PASSWORD: ${{ secrets.FANDOM_PASSWORD }}
        FANDOM_USERNAME: ${{ secrets.FANDOM_USERNAME }}
        FANDOM_WIKI: bitomic

        WIKIPEDIA_API: https://es.wikipedia.org/w/api.php
        WIKIPEDIA_PASSWORD: ${{ secrets.WIKIPEDIA_PASSWORD }}
        WIKIPEDIA_USERNAME: ${{ secrets.WIKIPEDIA_USERNAME }}
      run: yarn test
